export const RECEIVE_BRANDS = 'RECEIVE_BRANDS';
export const RECEIVE_CARS = 'RECEIVE_CARS';
export const RECEIVE_MODELS = 'RECEIVE_MODELS';
export const SEARCH_BY_BRAND = 'SEARCH_BY_BRAND';
export const TOGGLE_SELECT_CAR = 'TOGGLE_SELECT_CAR';